# Generated by Django 4.1.5 on 2023-01-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0017_post_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField()),
                ('num', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dimension', models.CharField(choices=[('m2', 'м2'), ('pog_m', 'пог. м'), ('single', 'шт.'), ('point', 'точка'), ('percent', '%')], default='m2', max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='price.pricecategory')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='blog.post')),
            ],
        ),
    ]
