# Generated by Django 4.1.5 on 2023-01-20 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 20, 21, 56, 45, 321231), null=True),
        ),
    ]
