# Generated by Django 4.2.3 on 2023-07-28 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0027_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 28, 22, 17, 25, 88207), null=True),
        ),
    ]
