# Generated by Django 5.2 on 2025-05-02 20:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 2, 23, 24, 15, 728598), null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('dimension', models.CharField(default='м²', max_length=10)),
                ('use_in_calc', models.BooleanField(default=False, help_text='Использ в калькуляторе')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='blog.post')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='price.pricecategory')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
