# Generated by Django 5.2 on 2025-05-03 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 3, 10, 9, 40, 557487), null=True),
        ),
    ]
