# Generated by Django 5.2 on 2025-08-19 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['category', 'position', 'name']},
        ),
        migrations.AddField(
            model_name='price',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Число для порядка сортировки внутри категории (меньше = выше)', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 19, 12, 27, 74955), null=True),
        ),
    ]
