# Generated by Django 5.2 on 2025-05-03 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 4, 0, 9, 59, 355591), null=True),
        ),
    ]
