# Generated by Django 5.2 on 2025-08-19 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_options_price_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='position',
            field=models.FloatField(default=0.0, help_text='Число для порядка сортировки (меньше = выше). Можно использовать дроби для точной вставки между элементами.', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 19, 48, 59, 960009), null=True),
        ),
    ]
