# Generated by Django 4.1.5 on 2023-01-20 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_alter_price_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='price',
            name='num',
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 20, 22, 9, 9, 181548), null=True),
        ),
    ]
