# Generated by Django 4.1.5 on 2023-01-21 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_alter_price_options_remove_price_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='dimension',
            field=models.CharField(default='м²', max_length=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 21, 13, 22, 56, 854482), null=True),
        ),
    ]
