# Generated by Django 4.1.5 on 2023-01-22 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_alter_price_dimension_alter_price_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecategory',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 22, 11, 54, 48, 338861), null=True),
        ),
    ]
