# Generated by Django 4.1.5 on 2023-01-26 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_alter_pricecategory_options_pricecategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 26, 21, 26, 59, 376935), null=True),
        ),
    ]
