# Generated by Django 4.1.5 on 2023-02-01 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0017_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 1, 23, 16, 10, 738541), null=True),
        ),
    ]
