# Generated by Django 4.1.5 on 2023-02-05 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0018_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 5, 18, 57, 19, 912456), null=True),
        ),
    ]
