# Generated by Django 4.1.5 on 2023-04-10 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0022_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 10, 20, 41, 28, 477846), null=True),
        ),
    ]
