# Generated by Django 4.1.5 on 2023-04-19 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0025_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 22, 29, 48, 694919), null=True),
        ),
    ]
