# Generated by Django 4.2.3 on 2023-07-28 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0026_alter_price_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 28, 21, 14, 46, 413314), null=True),
        ),
    ]
