version: '3.9'
services:
  web:
    build: ./django
      # context: .
      # dockerfile: Dockerfile
    image: r199-dev
    restart: unless-stopped
    user: 1000:1000
    env_file:
      - ./django/.env
    ports:
      - "8000:8000"
    container_name: r199_dev
    volumes:
      - ./django:/code:rw
      - ./django/cache:/code/cache:rw
    command: "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
   build: ./db
   container_name: r199_db
   restart: unless-stopped
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   env_file:
     - ./db/.db.env


volumes:
  postgres_data:
#networks:
#  djangonet:
