version: '3.9'
services:

  #django
  web:
    build:
      context: ./django
      dockerfile: Dockerfile-PROD
    image: r199-prod
    restart: unless-stopped
    user: 1000:1000
    ports:
      - "8014:8000"
    container_name: r199_prod
    env_file:
      - ./django/.env.prod
    volumes:
      - ./django:/code
    depends_on:
      - db

  # postgres
  db:
   build: ./db
   container_name: r199_db
   restart: unless-stopped
   volumes:
     - postgres_data:/var/lib/postgresql/data/
   env_file:
     - ./db/.db.env

volumes:
  postgres_data:
