# Generated by Django 4.2.3 on 2023-07-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0027_alter_price_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150, verbose_name='Название материала')),
                ('amount', models.IntegerField(verbose_name='Расход ')),
                ('unit', models.IntegerField(verbose_name='Единицы измерения')),
                ('dimension', models.CharField(default='м²', max_length=10, verbose_name='Площадь/Объем')),
                ('thickness', models.IntegerField(default=10, verbose_name='Толщина слоя')),
                ('boxing', models.IntegerField(blank=True, default=20, null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc', to='price.price')),
            ],
        ),
    ]
