# Generated by Django 5.2 on 2025-05-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('room_type_description', models.CharField(default='Простое/Сложное', max_length=500, verbose_name='Описание помещения')),
                ('perimetr', models.PositiveIntegerField(default=7300, verbose_name='Периметр помещения')),
                ('length', models.PositiveIntegerField(default=5200, verbose_name='Длина помещения')),
                ('width', models.PositiveIntegerField(default=3400, verbose_name='Ширина помещения')),
                ('height', models.PositiveIntegerField(default=2600, verbose_name='Высота помещения')),
                ('door_width', models.PositiveIntegerField(default=800, verbose_name='Ширина двери')),
                ('door_height', models.PositiveIntegerField(default=2000, verbose_name='Высота двери')),
                ('window_width', models.PositiveIntegerField(default=1550, verbose_name='Ширина окна')),
                ('window_height', models.PositiveIntegerField(default=1450, verbose_name='Высота окна')),
            ],
        ),
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150, verbose_name='Название материала')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Расход')),
                ('unit', models.CharField(default='кг', max_length=30, verbose_name='Единицы измерения')),
                ('dimension', models.CharField(default='м²', max_length=10, verbose_name='Площадь/Объем')),
                ('thickness', models.IntegerField(blank=True, default=0, null=True, verbose_name='Толщина слоя (мм)')),
                ('boxing', models.IntegerField(blank=True, default=20, null=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calc', to='price.price')),
            ],
        ),
    ]
