# Generated by Django 4.2.3 on 2023-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_calc_amount_alter_calc_thickness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcSquare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=20)),
                ('perimetr', models.PositiveIntegerField(default=7300, verbose_name='Периметр помещения')),
                ('length', models.PositiveIntegerField(default=5200, verbose_name='Длина помещения')),
                ('width', models.PositiveIntegerField(default=3400, verbose_name='Ширина помещения')),
                ('height', models.PositiveIntegerField(default=2600, verbose_name='Высота помещения')),
                ('door_width', models.PositiveIntegerField(default=800, verbose_name='Ширина двери')),
                ('door_height', models.PositiveIntegerField(default=2000, verbose_name='Высота двери')),
                ('window_width', models.PositiveIntegerField(default=2000, verbose_name='Ширина окна')),
                ('window_height', models.PositiveIntegerField(default=2000, verbose_name='Высота окна')),
            ],
        ),
        migrations.AlterField(
            model_name='calc',
            name='thickness',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Толщина слоя (мм)'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='unit',
            field=models.CharField(default='кг', max_length=30, verbose_name='Единицы измерения'),
        ),
    ]
