# Generated by Django 4.2.3 on 2023-08-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_calcsquare_alter_calc_thickness_alter_calc_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='calcsquare',
            name='room_type_description',
            field=models.CharField(default='Простое/Сложное', max_length=500, verbose_name='Описание помещения'),
        ),
        migrations.AlterField(
            model_name='calcsquare',
            name='window_height',
            field=models.PositiveIntegerField(default=1450, verbose_name='Высота окна'),
        ),
        migrations.AlterField(
            model_name='calcsquare',
            name='window_width',
            field=models.PositiveIntegerField(default=1550, verbose_name='Ширина окна'),
        ),
    ]
