# Generated by Django 4.1.5 on 2023-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_promoabout_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='main_image',
            field=models.ImageField(default='', upload_to='about/'),
        ),
    ]
