# Generated by Django 4.1.5 on 2023-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_social_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='font_awesome_code',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
