# Generated by Django 4.1.5 on 2023-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlink',
            name='font_awesome_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contactlink',
            name='value',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='icon',
            field=models.FileField(null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='contactlink',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
