# Generated by Django 4.2.5 on 2024-04-23 13:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('about_hero_image', models.ImageField(default='', help_text='about_hero_image 1920x1280', upload_to='about/')),
                ('main_image', models.ImageField(default='', help_text='add main about img 1280x853', upload_to='about/')),
                ('name', models.CharField(max_length=25)),
                ('slogan', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('font_awesome_icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('message', models.TextField(max_length=5000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='HomeHeroSlogans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_section', models.PositiveSmallIntegerField(default=0)),
                ('small_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('title_image', models.ImageField(blank=True, default='', null=True, upload_to='about/home_hero')),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, default='', null=True, upload_to='icons/social')),
                ('font_awesome_code', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=1000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_promo', to='contact.about')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('alt', models.CharField(max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='contact.about')),
            ],
        ),
    ]
