# Generated by Django 4.1.5 on 2023-01-16 14:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallPromoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', ckeditor.fields.RichTextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='mini_text',
        ),
        migrations.AddField(
            model_name='about',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
