# Generated by Django 4.1.5 on 2023-01-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_smallpromoabout_remove_about_mini_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slogan',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
