# Generated by Django 4.1.5 on 2023-01-16 16:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_promoabout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallpromoabout',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
