# Generated by Django 4.1.5 on 2023-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_smallpromoabout_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallpromoabout',
            name='text',
        ),
        migrations.RemoveField(
            model_name='smallpromoabout',
            name='title',
        ),
    ]
