# Generated by Django 4.1.5 on 2023-01-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_remove_smallpromoabout_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoabout',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
