# Generated by Django 4.1.5 on 2023-01-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_social_font_awesome_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlogans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('title_image', models.ImageField(blank=True, default='', null=True, upload_to='about/home_hero')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='SmallPromoAbout',
        ),
    ]
