# Generated by Django 4.1.5 on 2023-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_alter_homeheroslogans_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeheroslogans',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='homeheroslogans',
            name='hero_section',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
