# Generated by Django 4.1.5 on 2023-01-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0016_contactlink_font_awesome_icon_contactlink_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlink',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
