# Generated by Django 4.1.5 on 2023-02-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_alter_contactlink_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlink',
            options={'ordering': ('pk',)},
        ),
    ]
