# Generated by Django 4.1.5 on 2023-02-05 15:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_alter_contactlink_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email',
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=30, region=None),
        ),
    ]
