# Generated by Django 4.1.5 on 2023-01-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_description_post_keywords_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
