# Generated by Django 4.1.5 on 2023-01-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_slugy_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slugy',
            new_name='slug',
        ),
    ]
