# Generated by Django 4.1.5 on 2023-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
