# Generated by Django 5.2 on 2025-05-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, default='', help_text='Meta title', max_length=300, null=True),
        ),
    ]
