# Generated by Django 4.1.5 on 2023-01-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slugy',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
