# Generated by Django 4.1.5 on 2023-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]
