# syntax=docker/dockerfile:1
# Pull base image
FROM python:3.12-alpine

# Set environment variables
ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
WORKDIR /code

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY ./uget_to_get.txt /usr/local/lib/python3.12/site-packages/snowpenguin/django/recaptcha3/fields.py

# Copy entrypoint.sh
COPY ./entrypoint.sh .
RUN chmod +x entrypoint.sh

#Copy all django
#COPY . .

#Change own
#RUN mkdir cache && chown -cR 1001:1001 cache
# run entrypoint.sh
ENTRYPOINT ["sh", "entrypoint.sh"]


