# Generated by Django 4.2.3 on 2023-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Расход'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='thickness',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Толщина слоя'),
        ),
        migrations.AlterField(
            model_name='calc',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Единицы измерения'),
        ),
    ]
